"""Menu trees for both application modes, mirroring the original app (APP_BLUEPRINT.md).

Each leaf is (label, target). target is either:
  "e:<endpoint>"  -> url_for(endpoint)
  "s:<gridkey>"   -> url_for('screen', key=gridkey)
  ""              -> not yet wired (shown disabled)
"""

PAYROLL_MENU = [
    ("Database", [
        ("Table Codes", "s:tablecodes"),
        ("Tax Table", "s:taxtable"),
        ("SSS Table", "s:ssstable"),
        ("PhilHealth Table", "s:phtable"),
        ("—", ""),
        ("Company", "s:company"),
        ("Payroll Items", "s:payitem"),
        ("Overtime Rates", "s:otrates"),
        ("Shift Table", "s:shifttable"),
        ("—", ""),
        ("Employee Data", "e:employees"),
    ]),
    ("Transactions", [
        ("Rate Change", "s:ratechange"),
        ("Department Change", "s:deptchange"),
        ("Job Position Change", "s:jobchange"),
        ("—", ""),
        ("Loans", "s:loans"),
        ("—", ""),
        ("YTD Data Adjustments", "r:ytd_adjust"),
        ("Previous Employment YTD Gross and Tax", "r:prev_emp_ytd"),
    ]),
    ("Attendance", [
        ("Holiday Table", "s:holidays"),
        ("Employee Shifts", "s:empshift"),
        ("—", ""),
        ("Time Card Update", "r:tc_view"),
        ("Time Card Inquiry", "r:tc_view"),
        ("—", ""),
        ("Daily Attendance Report", "r:att_daily"),
        ("Daily Overtime Report", "r:att_ot"),
        ("Attendance Exception Report", "r:att_exception"),
    ]),
    ("Payroll Processing", [
        ("Define Pay Period", "s:payperiod"),
        ("Post Attendance Transactions", "r:post_attend"),
        ("—", ""),
        ("Overtime Entry", "e:payroll_ot"),
        ("Leaves/Absences Entry", "s:leavetran"),
        ("Additional Earnings/Deductions Entry", "r:addl_entry"),
        ("—", ""),
        ("Payroll Calculation", "e:payroll_compute"),
        ("Payroll Register (compute all)", "e:payroll_compute_all"),
        ("Rate / Statutory Calculator", "e:calculator"),
        ("Verify Engine vs History", "e:engine_verify"),
        ("—", ""),
        ("Payroll Register", "e:payroll"),
        ("Deduction Register", "r:ded_register"),
        ("Payslip (pick employee)", "e:employees"),
        ("Bank Summary", "r:bank_summary"),
        ("Cash Summary", "r:cash_summary"),
        ("—", ""),
        ("Payroll Close", "s:payperiod"),
    ]),
    ("Inquiries/Reports", [
        ("Employee Data", "e:employees"),
        ("Masterlist By Department", "s:ml_dept"),
        ("Masterlist by Pay Group", "s:ml_paygroup"),
        ("Masterlist by Shift", "s:ml_shift"),
        ("—", ""),
        ("SSS Monthly Remittance (list)", "s:rpt_sss"),
        ("PhilHealth Monthly Remittance (list)", "s:rpt_phic"),
        ("HDMF Monthly Remittance (list)", "s:rpt_hdmf"),
        ("—", ""),
        ("SSS R-3 Form", "f:sss"),
        ("PhilHealth RF-1 Form", "f:philhealth"),
        ("HDMF MCRF Form", "f:hdmf"),
        ("BIR Alphalist / 2316", "f:alphalist"),
        ("—", ""),
        ("Loans History", "s:rpt_loans"),
    ]),
    ("HR »", [("Switch to HR Application", "mode:HR")]),
]

HR_MENU = [
    ("Database", [
        ("Users", "s:users"),
        ("Table Codes", "s:tablecodes"),
        ("Banks", "s:banks"),
        ("—", ""),
        ("Company", "s:company"),
        ("Position Titles", "s:jobcode"),
        ("Divisions", "s:division"),
        ("Departments", "s:department"),
        ("Sections", "s:section"),
        ("Shift Table", "s:shifttable"),
        ("—", ""),
        ("Employee Data", "e:employees"),
    ]),
    ("Transactions", [
        ("Company Change", "s:companychg"),
        ("Department Change", "s:deptchange"),
        ("Job Position Change", "s:jobchange"),
        ("Rate Change", "s:ratechange"),
        ("—", ""),
        ("Leaves and Absences", "s:leavetran"),
    ]),
    ("Inquiries/Reports", [
        ("Employee Data Inquiry", "e:employees"),
        ("Hired This Period", "s:hr_hired"),
        ("Due for Regularization", "s:hr_dueregular"),
        ("Resigned This Period", "s:hr_resigned"),
        ("Birthday Celebrants", "s:hr_birthdays"),
        ("—", ""),
        ("Masterlist by Department", "s:ml_dept"),
        ("Headcount By Dept/Section/Status", "s:hr_headcount"),
        ("Years of Service Report", "s:hr_yos"),
        ("Leaves Balances", "s:hr_leavebal"),
    ]),
    ("Inquiries/Reports-2", [
        ("Employee List By Length of Service", "s:hr_yos"),
        ("Employee Training Report", "s:hr_training"),
        ("Employee List By Blood Type", "s:hr_blood"),
        ("Educational Attainment", "s:hr_education"),
        ("Medical History", "s:hr_medical"),
    ]),
    ("Payroll »", [("Switch to Payroll Application", "mode:PY")]),
]
