"""Prepare employee child tables for editing (idempotent). Run once per database.

For each table:
  1. add a stable surrogate key `rowid` (identity) — used to edit/delete rows,
  2. drop the restrictive composite primary key (natural keys are messy/absent;
     rowid is the identity now), and
  3. relax NOT NULL on the natural-key columns so partial inserts work.

Integrity in this system was always app-enforced (0 DB foreign keys), so this is safe.
"""
from db import get_conn

TABLES = ["edutrain", "training", "workexp", "dependents", "leaves", "leavetran",
          "medical", "appraisal", "discipline", "edoc", "fixallow", "fixded", "loans"]
KEEP_NN = {"company", "emp_id", "rowid"}


def main():
    with get_conn() as c:
        with c.cursor() as cur:
            for t in TABLES:
                cur.execute(f'ALTER TABLE {t} ADD COLUMN IF NOT EXISTS rowid bigint GENERATED BY DEFAULT AS IDENTITY;')
                cur.execute(f'ALTER TABLE {t} DROP CONSTRAINT IF EXISTS {t}_pkey;')
                cur.execute("SELECT column_name FROM information_schema.columns "
                            "WHERE table_name=%s AND is_nullable='NO'", (t,))
                for col in [r["column_name"] for r in cur.fetchall() if r["column_name"] not in KEEP_NN]:
                    cur.execute(f'ALTER TABLE {t} ALTER COLUMN "{col}" DROP NOT NULL;')
        c.commit()
    print(f"Prepared {len(TABLES)} employee child tables for editing (rowid + relaxed keys).")


if __name__ == "__main__":
    main()
