"""Create the rebuild's payroll working tables (idempotent). Run once per database.

  ot_entry     — per-employee overtime hours entered for a period (feeds the calc)
  period_close — marks a period as posted/closed (guards re-posting; shows status)
"""
from db import get_conn

DDL = [
    """CREATE TABLE IF NOT EXISTS ot_entry (
        rowid       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company     varchar(3)  NOT NULL,
        payyear     int         NOT NULL,
        paymonth    int         NOT NULL,
        payperiod   varchar(1)  NOT NULL,
        emp_id      varchar(6)  NOT NULL,
        payitem     varchar(3)  NOT NULL,
        hours       numeric(9,2) NOT NULL DEFAULT 0,
        changeby    varchar(10),
        changedate  timestamp
    );""",
    "CREATE INDEX IF NOT EXISTS ix_ot_entry_period ON ot_entry (company, payyear, paymonth, payperiod);",
    """CREATE TABLE IF NOT EXISTS period_close (
        company    varchar(3) NOT NULL,
        payyear    int        NOT NULL,
        paymonth   int        NOT NULL,
        payperiod  varchar(1) NOT NULL,
        closed_by  varchar(10),
        closed_at  timestamp,
        PRIMARY KEY (company, payyear, paymonth, payperiod)
    );""",
]


def main():
    with get_conn() as c:
        with c.cursor() as cur:
            for stmt in DDL:
                cur.execute(stmt)
        c.commit()
    print("Payroll working tables ready: ot_entry, period_close")


if __name__ == "__main__":
    main()
