"""Employee mobile time clock — one-time table setup (idempotent). Run once per database.

  emp_auth — badge + PIN login for the employee portal (separate from back-office `users`)
  punchlog — immutable raw punch events from phones (the audit trail; timecardtr/timecard
             are rebuilt from these, never the other way around)
"""
from db import get_conn


def main():
    with get_conn() as c:
        with c.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS emp_auth (
                  company    varchar(3)  NOT NULL,
                  emp_id     varchar(6)  NOT NULL,
                  pin_hash   text        NOT NULL,
                  must_change boolean    NOT NULL DEFAULT true,
                  active     boolean     NOT NULL DEFAULT true,
                  created_by varchar(10),
                  created_at timestamp,
                  changed_at timestamp,
                  PRIMARY KEY (company, emp_id)
                )""")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS punchlog (
                  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  company    varchar(3)  NOT NULL,
                  emp_id     varchar(6)  NOT NULL,
                  punch_at   timestamptz NOT NULL,
                  local_date date        NOT NULL,
                  local_hhmm numeric(4,0) NOT NULL,
                  kind       varchar(3)  NOT NULL,
                  lat        numeric(9,6),
                  lng        numeric(9,6),
                  accuracy   numeric(7,1),
                  ip         varchar(45),
                  ua         varchar(200)
                )""")
            cur.execute("CREATE INDEX IF NOT EXISTS punchlog_day ON punchlog (company, emp_id, local_date)")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS time_request (
                  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  company    varchar(3)  NOT NULL,
                  emp_id     varchar(6)  NOT NULL,
                  rtype      varchar(2)  NOT NULL,
                  reqdate    date        NOT NULL,
                  hours      numeric(5,2) NOT NULL,
                  reason     varchar(120),
                  status     varchar(1)  NOT NULL DEFAULT 'P',
                  created_at timestamptz NOT NULL,
                  decided_by varchar(10),
                  decided_at timestamp
                )""")
            cur.execute("CREATE INDEX IF NOT EXISTS time_request_emp ON time_request (company, emp_id, created_at DESC)")
            cur.execute("""
                CREATE TABLE IF NOT EXISTS leave_request (
                  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  company    varchar(3)  NOT NULL,
                  emp_id     varchar(6)  NOT NULL,
                  payitem    varchar(3)  NOT NULL,
                  frdate     date        NOT NULL,
                  todate     date        NOT NULL,
                  days       numeric(5,2) NOT NULL,
                  reason     varchar(120),
                  status     varchar(1)  NOT NULL DEFAULT 'P',
                  created_at timestamptz NOT NULL,
                  decided_by varchar(10),
                  decided_at timestamp
                )""")
            cur.execute("CREATE INDEX IF NOT EXISTS leave_request_emp ON leave_request (company, emp_id, created_at DESC)")
        c.commit()
    print("emp_auth + punchlog + time_request ready.")


if __name__ == "__main__":
    main()
